#! /bin/sh
### BEGIN INIT INFO
# Provides:          temperature-server
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

PYTHON_PATH=/opt/python3.3.2/bin
TEMPERATURE_APP_PATH=/opt/temperature-server
#DAEMON=$PYTHON_PATH/python3 $TEMPERATURE_APP_PATH/temperature-server.py
#NAME=temperature-server

case "$1" in
start)   echo -n "Start temperature-server"
#   start-stop-daemon --chdir $TEMPERATURE_APP_PATH --start --quiet \
#       --pidfile /var/run/$NAME.pid --make-pidfile --exec $DAEMON || true
   /opt/python3.3.2/bin/python3 /opt/temperature-server/temperature-server.py &
   ;;
stop)   echo -n "Stop temperature-server"
   sudo killall temperature-server.py
   ;;
restart)
   $0 stop
   $0 start
        ;;
*)   echo "Usage: $0 start|stop|restart"
        exit 1
        ;;
esac
exit 0